# Stage 1: Build
FROM node:16 as builder

WORKDIR /app

COPY package*.json ./

# Install all dependencies.
RUN npm install

COPY . .

# Compile TypeScript to JavaScript.
RUN npm run build

# Stage 2: Run
FROM node:16

WORKDIR /app

COPY package*.json ./

# Install only production dependencies.
RUN npm install --only=production

# Copy built code from the builder stage.
COPY --from=builder /app/dist ./dist

# Run the web service on container startup.
CMD [ "npm", "start" ]

# Service runs on port 3000.
EXPOSE 3000
